#!/usr/bin/perl
use LWP::UserAgent;
use strict;
use warnings;
use DBI;
use DBD::mysql;

my $is_celsius=1; #set to 1 if using Celsius
my $output="";
my $attempts=0;
my $temp=0;  

#----------------------------------------------------------------------
# insert the values into the database
#----------------------------------------------------------------------
my $connection = ConnectToMySql();
# set the value of your SQL query
my $queryInsert = "insert into tempMonitor(tempValue) values(?) ";
my $queryGetCorrectionPar = "select value from parameters where Param like 'CorrectionValueTHSensor01'";

# prepare  statement for connecting to the database
my $statementInsert = $connection->prepare($queryInsert);

my $statementGet = $connection->prepare($queryGetCorrectionPar);
$statementGet->execute();
my $correctionValParam = $statementGet->fetchrow_array;

while ($output !~ /YES/g && $attempts < 5) {
        $output = `cat /sys/bus/w1/devices/28-*/w1_slave 2>&1`;
        if($output !~ /NO/g) {
                $output =~ /t=(\d+)/i;
                $temp = ($is_celsius) ? (($1 - $correctionValParam)  / 1000) : (($1 - $correctionValParam) / 1000) * 9/5 + 32;
		print "Temperature:".$temp;
	} 
        $attempts++;
	$statementInsert->execute($temp);
}

sub ConnectToMySql {
	my $database = "warmme";
	my $host = "localhost";
	my $userid = "root";
	my $passwd = "warmme";
	# assign the values to your connection variable
	my $connectionInfo="dbi:mysql:$database;$host";
	# make connection to database
	my $l_connection = DBI->connect($connectionInfo,$userid,$passwd);
	# the value of this connection is returned by the sub-routine
	return $l_connection;
}
